[project]
name = "bz-chess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "lightning>=2.5.2",
    "termcolor>=3.1.0",
    "torch>=2.7.1",
]
